# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2] 
patreon: https://www.patreon.com/user?u=72747187
ko_fi: https://ko-fi.com/wisdomfox
